---
- name: Do stuff
  hosts: tag_mysql_test_aws_kfir_01
  gather_facts: yes
  tasks:
  - name: Print instance public IPs
    debug:
      msg: "{{ hostvars[inventory_hostname].tags }}"

  - name: Print EC2 tags
    debug:
      var: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
